"""Load /data into the deployed tables. Owner: Kaylin.

    python scripts/seed_dynamodb.py

Expected files (shapes in docs/api.md, generated by scripts/make_seed_data.py):
    data/accounts.json       list of Account
    data/transactions.json   list of Transaction (history for every account)

Replaces everything in the Accounts and Transactions tables. Cases and Audit are left alone.

Table names: set ACCOUNTS_TABLE and TRANSACTIONS_TABLE to the sam deploy outputs. If they are
not set, this looks them up from the fraud-speed-bump stack.
"""

import json
import os
import sys
from pathlib import Path

os.environ.setdefault("AWS_PROFILE", "lpl-hackathon")
os.environ.setdefault("AWS_REGION", "us-east-1")

ROOT = Path(__file__).resolve().parent.parent
STACK_NAME = "fraud-speed-bump"
TABLE_OUTPUTS = {
    "ACCOUNTS_TABLE": "AccountsTableName",
    "TRANSACTIONS_TABLE": "TransactionsTableName",
    "CASES_TABLE": "CasesTableName",
    "AUDIT_TABLE": "AuditTableName",
}


def set_table_names_from_stack():
    """Fill in any table-name env vars that are missing, from the stack outputs."""
    if all(os.environ.get(var) for var in TABLE_OUTPUTS):
        return
    import boto3

    stack = boto3.client("cloudformation", region_name=os.environ["AWS_REGION"]).describe_stacks(StackName=STACK_NAME)
    outputs = {o["OutputKey"]: o["OutputValue"] for o in stack["Stacks"][0]["Outputs"]}
    for var, output_key in TABLE_OUTPUTS.items():
        os.environ.setdefault(var, outputs[output_key])


def main():
    set_table_names_from_stack()
    sys.path.insert(0, str(ROOT / "backend"))
    from common import db  # imported after the env vars are set

    accounts = json.loads((ROOT / "data" / "accounts.json").read_text())
    transactions = json.loads((ROOT / "data" / "transactions.json").read_text())
    loaded = db.load_seed_data(accounts, transactions)
    print(f"Loaded {loaded} accounts and {len(transactions)} transactions into {db.ACCOUNTS_TABLE} and {db.TRANSACTIONS_TABLE}")


if __name__ == "__main__":
    main()
